
name: test-actions

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - id: scan
        uses: deta/publish-pc-app@main
        with:
          app: "0fb6bb64-8561-4473-84d5-fb05fe8bafd5"
          desc: "Multiple micros test"
        env:
          DETA_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
