
name: test-actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v3.3.0
        with:
          node-version: '12'
      - uses: actions/setup-node@v3.3.0
        with:
          node-version: '14'      
      - name: check nvm location
        shell: bash -l -eo pipefail {0}
        run: echo $NVM_DIR

      - name: test nvm command
        shell: bash -l -eo pipefail {0}
        run: nvm ls
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
#       - id: install-python
#         run: |
#           sudo apt install python3.8
#           sudo apt install python3.9
      - id: scan
        uses: rohanshiva/actions@main
      - run: echo say goodbye!
        shell: bash
